### ISSUE TITLE
图片粘贴不正常的问题

### ISSUE THREAD

**Issue by miseryCN** [terrylinooo/githuber-md#48]
图片直接粘贴会报500错误，使用的是最新的1.9.0版本（直接从插件库装的也会出这个错误），不知道是不是我本地的问题。 开启了php错误日志发现是mime_content_type()这个函数没定义导致的错误。完整错误日志如下：
```php
[23-Apr-2019 16:55:10 Asia/Shanghai] PHP Fatal error:  Uncaught Error: Call to undefined function Githuber\Controller\mime_content_type() in /www/mywebsite.com/wp-content/plugins/githuber-md-1.9.0/src/Controllers/ImagePaste.php:81
Stack trace:
#0 /www/mywebsite.com/wp-includes/class-wp-hook.php(286): Githuber\Controller\ImagePaste->admin_githuber_image_paste('')
#1 /www/mywebsite.com/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /www/mywebsite.com/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /www/mywebsite.com/wp-admin/admin-ajax.php(167): do_action('wp_ajax_githube...')
#4 {main}
  thrown in /www/mywebsite.com/wp-content/plugins/githuber-md-1.9.0/src/Controllers/ImagePaste.php on line 81
```
因为用qq截图，默认是png格式的，所以直接把:
```php
//$file_mimetype = mime_content_type( $file['tmp_name'] );
```
替换成了：
```php
$file_mimetype = 'image/png';
```
就可以正常工作了。麻烦作者查看下，是程序的bug还是跟其他插件的兼容问题？

**Comment by terrylinooo** [comment]
mime_content_type 要用 php_fileinfo 這個套件，您的系統沒安裝。我再換其它通用的函式來驗證上傳的檔案。
主要是要增加安全性。今晚會更新。

**Comment by miseryCN** [comment]
非常感谢！
